### ISSUE TITLE
Create toast component(s)

### ISSUE THREAD

**Issue by psirenny** [spear-ai/ui#254]
React Aria Components doesn't have a Toast in their component library yet — even though Spectrum does. We'll use the [Radix Toast Primitive](https://www.radix-ui.com/primitives/docs/components/toast) for now.

I'm thinking of leaving the contents of a Toast under specified to allow for maximum flexibility. If our apps tend to consistently use the same Toast content we can codify stricter patterns? As always, going to refer to [TailwindUI](https://tailwindui.com/components/application-ui/overlays/notifications) but use [Radix Colors](https://www.radix-ui.com/colors). CatalystUI hasn't implemented toasts or notifications yet so I won't refer to it.

@eakbulut I noticed that Vercel.com has lots of settings pages with forms and they utilize a Toast to display a success notification on the bottom right. I figure that's a good way to proceed? It's the motivation for this issue.

**Comment by eakbulut** [comment]
I think Tailwind's notification component looks good. The condensed view is somewhat similar to Material Design's snackbar component which I like. That's the one we should stick with to keep it simple as long as the toast is triggered by user action (validation) and not a system event (notification).

As for placement, I believe the most show up on lower right due to user familiarity with Windows notifications appearing in that part of the screen for decades. But we should also keep in mind where the action button triggering the toast is within the page layout. If it's consistently at the bottom of the page/form, then a bottom placement for the toast seems fair.
